function example2()
% This file is part of the software library that reproduces 
% numerical experiments from the manuscript
%   Zvonimir Bujanović, Luka Grubišić, Daniel Kressner, Hei Yin Lam: 
%   "Subspace embedding with random Khatri-Rao products and its application to eigensolvers".
%
% Reproduces Example 2 from the manuscript.

    for n = [1000, 2000, 3000]
        fprintf( '\n\n---------- n=%d sylvester solver: backslash ----------\n', n );
        test_contour( example='sum-of-squares-minus-xy', n=n, ...
            sylvester_solver='backslash', ...
            random_vectors_type='rank-one-multiply', ...
            n_quad_points=40, ...
            dim_right_projection=6 ); 
        fprintf( 'Press any key to continue...' );
        pause;

        close all;

        fprintf( '\n\n---------- n=%d sylvester solver: biCGstab, tol=1e-6 ----------\n', n );
        test_contour( example='sum-of-squares-minus-xy', n=n, ...
            sylvester_solver='biCGstab', ...
            biCGstab_tol=1e-6, ...
            random_vectors_type='rank-one', ...
            n_quad_points=40, ...
            dim_right_projection=6 ); 
        fprintf( 'Press any key to continue...' );
        pause;

        close all;

        fprintf( '\n\n---------- n=%d sylvester solver: biCGstab, tol=1e-10 ----------\n', n );
        test_contour( example='sum-of-squares-minus-xy', n=n, ...
            sylvester_solver='biCGstab', ...
            biCGstab_tol=1e-10, ...
            random_vectors_type='rank-one', ...
            n_quad_points=40, ...
            dim_right_projection=6 ); 
        fprintf( 'Press any key to continue...' );
        pause;

        close all;
    end
end
